AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless IT Support Automation Platform (DynamoDB + Lambda + API
  Gateway + S3)

Globals:
  Function:
    Runtime: python3.10
    Timeout: 10

Resources:

  TicketsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-Tickets
      AttributeDefinitions:
        - AttributeName: ticketId
          AttributeType: S
      KeySchema:
        - AttributeName: ticketId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  TicketProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-TicketProcessor
      Handler: ticket_processor.lambda_handler
      CodeUri: ../src/lambda/
      Environment:
        Variables:
          TABLE_NAME: !Ref TicketsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TicketsTable
      Events:
        CreateTicketApi:
          Type: Api
          Properties:
            Path: /tickets
            Method: post

  StaticSiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-frontend-${AWS::AccountId}
      WebsiteConfiguration:
        IndexDocument: index.html

Outputs:
  TicketsTableName:
    Value: !Ref TicketsTable
    Export:
      Name: !Sub ${AWS::StackName}-TicketsName

  FrontendBucketName:
    Value: !Ref StaticSiteBucket
    Export:
      Name: !Sub ${AWS::StackName}-FrontendBucket
  # Note: SAM/CFN will show the API endpoint in the sam deploy output.